version: "3"

services:
  mongo: 
    image: mongo
    restart: "always"
    volumes: 
      - ./.dbcache/mongo/data:/data/db
    ports:
      - "27019:27017"   # local : container
    networks:
      - backend
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
  api:
    image: node:12.18.3-slim
    ports:
      - "3300:3000"
    networks:
      - backend
    working_dir: "/home/node/app"
    volumes:
      - ./:/home/node/app
    command: "npm start"

networks:
  backend:
    driver: "bridge"